channels:
- conda-forge
dependencies:
- python=3.12.3
- pip<=24.3.1
- pip:
  - mlflow==2.19.0
  - cloudpickle==3.1.0
  - numpy==2.2.1
  - pandas==2.2.3
  - torch==2.5.1
  - tqdm==4.67.1
name: mlflow-env
